on:
  push:
    paths:
      - '**/*.nix'
      - flake.lock
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes

jobs:
  checks:
    runs-on: nix
    steps:
      - name: Install dependencies
        run: >
          nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Flake checks
        run: nix flake check
